baseURL = 'https://lauyh.github.io'
languageCode = 'en-us'
title = 'Yee Heng Programming Notes'
theme = 'risotto'
author = "Lau Yee Heng"
copyright = "© 2021 Yee Heng"
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true

sectionPagesMenu = "main"

[params]

[params.theme]
palette = "gruvbox-dark"
mode = "dark-mode"

# Sidebar: about/bio
[params.about]
title = "risotto"
description = "A [hugo](https://gohugo.io) theme inspired by terminal ricing."
logo = "images/rice.svg"

[[params.socialLinks]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/lauyh"

[[params.socialLinks]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:lauyh87@gmail.com"
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"